import Head from 'next/head';
// import Image from 'next/image';
import styles from '../../styles/Home.module.scss';
// import { Inter } from 'next/font/google';
// const inter = Inter({ subsets: ['latin'] });
import DisplayGallery from '@/components/DisplayGallery/DisplayGallery';

export default function Home() {
	const imageGrid = {
		title: 'Waist Coat Collection',
		images: [
			{
				src: '/kurta/50.png',
				text: 'Emerald Waist Coat',
			},
			{
				src: '/kurta/51.png',
				text: 'Ivory Textured',
			},
			{
				src: '/kurta/52.png',
				text: 'Royal Blue Velvet',
			},
			{
				src: '/kurta/53.png',
				text: 'Rusty Silk',
			},
			{
				src: '/kurta/54.png',
				text: 'Pearl White Coat',
			},
			{
				src: '/kurta/55.png',
				text: 'Burgundy Prince',
			},
			{
				src: '/kurta/56.png',
				text: 'Classic Charcoal',
			},
			{
				src: '/kurta/57.png',
				text: 'Midnight Gold',
			},
			{
				src: '/kurta/58.png',
				text: 'Saffron Velvet',
			},
			{
				src: '/kurta/59.png',
				text: 'Forest Green Silk',
			},
			{
				src: '/kurta/60.png',
				text: 'Navy Tradition',
			},
			{
				src: '/kurta/61.png',
				text: 'Maroon Majesty',
			},
		],
	};

	return (
		<>
			<Head>
				<title>Waist Coats | Zoll & Metér</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/zmlogo.png" />
			</Head>
			<main className={`${styles.homepage}`}>
				{/* <h1 className={`${styles.heading} ${styles.text}`}>ZOLL & METER</h1> */}
				{/* <div className={`${styles.window}`}>
				<div className={`${styles.box}`}>
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
				</div>
			</div> */}
				<DisplayGallery imageGrid={imageGrid}></DisplayGallery>
				<footer></footer>
			</main>
		</>
	);
}
