import Head from 'next/head';
// import Image from 'next/image';
import styles from '../../styles/Home.module.scss';
// import { Inter } from 'next/font/google';
// const inter = Inter({ subsets: ['latin'] });
import DisplayGallery from '@/components/DisplayGallery/DisplayGallery';

export default function Home() {
	const imageGrid = {
		title: 'Festive Collection',
		images: [
			{
				src: '/kurta/80.png',
				text: 'Royal Ivory Sherwani',
			},
			{
				src: '/suit/velvet-green-2.png',
				text: 'Velvet Green Gala Suit',
			},
			{
				src: '/thobe/Arabi/10.png',
				text: 'Signature Thobe',
			},
			{
				src: '/kurta/12.png',
				text: 'Embroidered Kurta',
			},
			{
				src: '/suit/rusty-1.png',
				text: 'Sunset Evening Coat',
			},
			{
				src: '/kurta/3.png',
				text: 'Traditional Silk',
			},
			{
				src: '/suit/premium-charcoal.png',
				text: 'Luxe Charcoal Suit',
			},
			{
				src: '/thobe/Arabi/5.png',
				text: 'Grand Arabi Thobe',
			},
			{
				src: '/kurta/85.png',
				text: 'Burgundy Prince',
			},
			{
				src: '/suit/navy-pinstripe.png',
				text: 'Navy Pinstripe Suit',
			},
			{
				src: '/kurta/11.png',
				text: 'Deep Water Luxury',
			},
			{
				src: '/thobe/Arabi/20.png',
				text: 'Royal Arabi',
			},
		],
	};

	return (
		<>
			<Head>
				<title>Festive Collection | Zoll & Metér</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/zmlogo.png" />
			</Head>
			<main className={`${styles.homepage}`}>
				{/* <h1 className={`${styles.heading} ${styles.text}`}>ZOLL & METER</h1> */}
				{/* <div className={`${styles.window}`}>
				<div className={`${styles.box}`}>
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
				</div>
			</div> */}
				<DisplayGallery imageGrid={imageGrid}></DisplayGallery>
				<footer></footer>
			</main>
		</>
	);
}
