import Head from 'next/head';
// import Image from 'next/image';
import styles from '../../styles/Home.module.scss';
// import { Inter } from 'next/font/google';
// const inter = Inter({ subsets: ['latin'] });
import DisplayGallery from '@/components/DisplayGallery/DisplayGallery';

export default function Home() {
	const imageGrid = {
		title: 'Suits Collection',
		images: [
			{
				src: '/suit/black-3.png',
				text: 'Classic Black Suit',
			},
			{
				src: '/suit/rusty-1.png',
				text: 'Rusty Evening Suit',
			},
			{
				src: '/suit/velvet-green-2.png',
				text: 'Velvet Green Gala Suit',
			},
			{
				src: '/suit/premium-charcoal.png',
				text: 'Premium Charcoal Suit',
			},
			{
				src: '/suit/navy-pinstripe.png',
				text: 'Navy Pinstripe Double-Breasted',
			},
			{
				src: '/suit/burgundy-tuxedo.png',
				text: 'Burgundy Velvet Tuxedo',
			},
			{
				src: '/suit/beige-linen.png',
				text: 'Beige Linen Summer Suit',
			},
			{
				src: '/suit/black-peak-lapel.png',
				text: 'Modern Black Peak Lapel',
			},
			{
				src: '/suit/download.jpeg',
				text: 'Traditional Suite A',
			},
			{
				src: '/suit/download (1).jpeg',
				text: 'Traditional Suite B',
			},
			{
				src: '/suit/download (2).jpeg',
				text: 'Traditional Suite C',
			},
			{
				src: '/suit/download (3).jpeg',
				text: 'Traditional Suite D',
			},
		],
	};

	return (
		<>
			<Head>
				<title>Suits | Zoll & Metér</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/zmlogo.png" />
			</Head>
			<main className={`${styles.homepage}`}>
				{/* <h1 className={`${styles.heading} ${styles.text}`}>ZOLL & METER</h1> */}
				{/* <div className={`${styles.window}`}>
				<div className={`${styles.box}`}>
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
				</div>
			</div> */}
				<DisplayGallery imageGrid={imageGrid}></DisplayGallery>
				<footer></footer>
			</main>
		</>
	);
}
