import Head from 'next/head';
// import Image from 'next/image';
import styles from '../../styles/Home.module.scss';
// import { Inter } from 'next/font/google';
// const inter = Inter({ subsets: ['latin'] });
import DisplayGallery from '@/components/DisplayGallery/DisplayGallery';

export default function Home() {
	const imageGrid = {
		title: 'Thobe Collection',
		images: [
			{
				src: '/thobe/Arabi/1.png',
				text: 'Classic Arabi 1',
			},
			{
				src: '/thobe/Arabi/2.png',
				text: 'Classic Arabi 2',
			},
			{
				src: '/thobe/Arabi/3.png',
				text: 'Classic Arabi 3',
			},
			{
				src: '/thobe/Arabi/4.png',
				text: 'Classic Arabi 4',
			},
			{
				src: '/thobe/Arabi/5.png',
				text: 'Classic Arabi 5',
			},
			{
				src: '/thobe/Arabi/6.png',
				text: 'Classic Arabi 6',
			},
			{
				src: '/thobe/Arabi/7.png',
				text: 'Classic Arabi 7',
			},
			{
				src: '/thobe/Arabi/8.png',
				text: 'Classic Arabi 8',
			},
			{
				src: '/thobe/Arabi/9.png',
				text: 'Classic Arabi 9',
			},
			{
				src: '/thobe/Arabi/10.png',
				text: 'Classic Arabi 10',
			},
			{
				src: '/thobe/Arabi/11.png',
				text: 'Classic Arabi 11',
			},
			{
				src: '/thobe/Arabi/12.png',
				text: 'Classic Arabi 12',
			},
		],
	};

	return (
		<>
			<Head>
				<title>Thobes | Zoll & Metér</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/zmlogo.png" />
			</Head>
			<main className={`${styles.homepage}`}>
				{/* <h1 className={`${styles.heading} ${styles.text}`}>ZOLL & METER</h1> */}
				{/* <div className={`${styles.window}`}>
				<div className={`${styles.box}`}>
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
				</div>
			</div> */}
				<DisplayGallery imageGrid={imageGrid}></DisplayGallery>
				<footer></footer>
			</main>
		</>
	);
}
