import Head from 'next/head';
// import Image from 'next/image';
import styles from '../../styles/Home.module.scss';
// import { Inter } from 'next/font/google';
// const inter = Inter({ subsets: ['latin'] });
import DisplayGallery from '@/components/DisplayGallery/DisplayGallery';

export default function Home() {
	const imageGrid = {
		title: '',
		images: [
			{
				src: '/img1.webp',
				text: 'Morning Mist',
			},
			{
				src: '/img2.webp',
				text: 'Pine Green',
			},
			{
				src: '/img3.webp',
				text: 'Seafoam Green',
			},
			{
				src: '/img4.webp',
				text: 'Dusty Yale',
			},
			{
				src: '/img5.webp',
				text: 'Sterling Palms',
			},
			{
				src: '/img6.webp',
				text: 'Vintage Cobalt',
			},
			{
				src: '/img7.jpg',
				text: 'Castlaton Shine',
			},
			{
				src: '/img8.webp',
				text: 'Chanterelle Beige',
			},
		],
	};

	return (
		<>
			<Head>
				<title>Kurtas</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/zmlogo.png" />
			</Head>
			<main className={`${styles.homepage}`}>
				{/* <h1 className={`${styles.heading} ${styles.text}`}>ZOLL & METER</h1> */}
				{/* <div className={`${styles.window}`}>
				<div className={`${styles.box}`}>
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
				</div>
			</div> */}
				<DisplayGallery imageGrid={imageGrid}></DisplayGallery>
				<footer></footer>
			</main>
		</>
	);
}
