import Head from 'next/head';
// import Image from 'next/image';
import styles from '../../styles/Home.module.scss';
// import { Inter } from 'next/font/google';
// const inter = Inter({ subsets: ['latin'] });
import DisplayGallery from '@/components/DisplayGallery/DisplayGallery';

export default function Home() {
	// const imageGrid = {
	// 	title: '',
	// 	images: [
	// 		{
	// 			src: '/img1.webp',
	// 			text: 'Morning Mist',
	// 		},
	// 		{
	// 			src: '/img2.webp',
	// 			text: 'Pine Green',
	// 		},
	// 		{
	// 			src: '/img3.webp',
	// 			text: 'Seafoam Green',
	// 		},
	// 		{
	// 			src: '/img4.webp',
	// 			text: 'Dusty Yale',
	// 		},
	// 		{
	// 			src: '/img5.webp',
	// 			text: 'Sterling Palms',
	// 		},
	// 		{
	// 			src: '/img6.webp',
	// 			text: 'Vintage Cobalt',
	// 		},
	// 		{
	// 			src: '/img7.jpg',
	// 			text: 'Castlaton Shine',
	// 		},
	// 		{
	// 			src: '/img8.webp',
	// 			text: 'Chanterelle Beige',
	// 		},
	// 	],
	// };

	const kurtas = {
		title: 'Kurtas',
		images: [
			{
				src: '/kurtas/kurta1.1.webp',
				text: 'Rustic Orange',
			},
			{
				src: '/kurtas/kurta2.1.webp',
				text: 'Nahua',
			},
			{
				src: '/kurtas/kurta3.1.webp',
				text: 'Aztec Kurta',
			},
			{
				src: '/kurtas/kurta4.1.webp',
				text: 'brunette',
			},
			{
				src: '/kurtas/kurta5.1.webp',
				text: 'Lapis',
			},
			{
				src: '/kurtas/kurta6.1.webp',
				text: 'Gwalior',
			},
			{
				src: '/kurtas/kurta7.1.webp',
				text: 'Asfar Kurta',
			},
			{
				src: '/kurtas/kurta8.1.webp',
				text: 'Zuhal',
			},
			{
				src: '/kurtas/kurta9.1.webp',
				text: 'Ilia',
			},
			{
				src: '/kurtas/kurta10.1.webp',
				text: 'Iyad',
			},
			{
				src: '/kurtas/kurta11.2.webp',
				text: 'Deep Water Kurta',
			},
			{
				src: '/kurtas/kurta12.1.webp',
				text: 'Arzoo A',
			},
		],
	};

	return (
		<>
			<Head>
				<title>Kurtas</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/zmlogo.png" />
			</Head>
			<main className={`${styles.homepage}`}>
				{/* <h1 className={`${styles.heading} ${styles.text}`}>ZOLL & METER</h1> */}
				{/* <div className={`${styles.window}`}>
				<div className={`${styles.box}`}>
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
					<Image className={`${styles.img}`} src="/img0.webp" alt="cloth" width="1200" height="600" priority={true} />
				</div>
			</div> */}
				<DisplayGallery imageGrid={kurtas}></DisplayGallery>
				<footer></footer>
			</main>
		</>
	);
}
