'use client';

import Head from 'next/head';
import Image from 'next/image';
import styles from './product.module.scss';
import { useState } from 'react';
import { useAppDispatch } from '@/lib/hooks';
import { addToCart } from '@/lib/features/cartSlice';
import { getProductById, type ProductData } from '@/lib/productData';

type Props = {
	params: {
		id: string;
	};
};

export default function Product({ params }: Props) {
	// Get product data based on ID from URL
	const productData: ProductData = getProductById(params.id);

	const [formData, setFormData] = useState({
		name: '',
		mobileNo: '',
		email: '',
		message: '',
	});

	const dispatch = useAppDispatch();
	const [selectedSize, setSelectedSize] = useState('');

	const handleAddToCart = () => {
		if (!selectedSize) {
			alert('Please select a size');
			return;
		}

		dispatch(
			addToCart({
				id: productData.id,
				title: productData.title,
				price: productData.mrp,
				size: selectedSize,
				quantity: 1,
				image: productData.images[0],
			})
		);
		alert('Added to cart!');
		setSelectedSize(''); // Reset size selection
	};

	const saveProduct = async (event: React.FormEvent) => {
		event.preventDefault();

		try {
			// Send inquiry to backend API
			const response = await fetch('/api/inquiries/upsert', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
				},
				body: JSON.stringify({
					...formData,
					product: productData.title,
				}),
			});

			const data = await response.json();
			if (response.ok && data.emailSent) {
				window.alert('Inquiry sent successfully! We will contact you soon.');
				// Reset form
				setFormData({
					name: '',
					mobileNo: '',
					email: '',
					message: '',
				});
			} else {
				window.alert('Failed to send inquiry. Please try again.');
			}
		} catch (error) {
			console.error('Error sending inquiry:', error);
			window.alert('An error occurred. Please try again later.');
		}
	};

	const handleChange = (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
		const { name, value } = event.target;
		setFormData((prev) => ({
			...prev,
			[name]: value,
		}));
	};

	return (
		<>
			<Head>
				<title>Product</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/zmlogo.png" />
			</Head>
			<main className={`${styles.main}`}>
				<>
					<div className={`${styles.images_holder}`}>
						{productData.images.map((imageSrc, index) => (
							<div key={index} className={`${styles.image_wrapper}`}>
								<Image
									className={`${styles.product_image}`}
									src={imageSrc}
									alt={productData.title}
									width="336"
									height="471"
									layout="responsive"
								/>
							</div>
						))}
					</div>
					<div className={`${styles.add_product_form}`}>
						<div className={`${styles.title}`}>
							<h1 className={`${styles.product_name}`}>
								{productData.title}
							</h1>
							<p className={`${styles.mrp}`}>
								MRP inclusive of all taxes
							</p>
							<p className={`${styles.price}`}>
								Rs. {productData.mrp}
							</p>
						</div>
						<p className={`${styles.sizes_text}`}>sizes</p>
						<div className={`${styles.sizes}`}>
							{productData.sizes.map((size, index) => (
								size && (
									<div
										key={index}
										className={`${styles.size} ${selectedSize === size ? styles.selected : ''}`}
										onClick={() => setSelectedSize(size)}
									>
										{size}
									</div>
								)
							))}
						</div>
						<div className={`${styles.notify}`} onClick={handleAddToCart}>
							<svg
								xmlns="http://www.w3.org/2000/svg"
								width="13"
								height="14"
								viewBox="0 0 13 14"
								fill="none"
							>
								<path
									d="M9.35986 4V5.5H8.36086V4H4.36286V5.5H3.35986V4H2.35986V5.119C2.35986 5.985 2.20286 7.019 1.96286 8.488L1.83286 9.263C1.49286 11.241 1.44486 11.543 1.39286 12.135C1.38186 12.258 1.37486 12.366 1.37186 12.461C1.74386 12.535 2.15986 12.609 2.60586 12.679C3.89586 12.879 5.17986 13 6.35986 13C6.46986 13 6.57986 12.999 6.69386 12.996C7.66386 12.974 8.69786 12.863 9.85186 12.679C9.92086 12.669 10.7249 12.526 11.3469 12.427C11.3424 12.3289 11.3358 12.2308 11.3269 12.133C11.2759 11.54 11.2269 11.23 10.8879 9.258L10.7579 8.488C10.5179 7.018 10.3599 5.985 10.3599 5.118V4H9.35986V4ZM3.35986 3V2.256C3.35986 0.71 4.48286 0 6.35986 0C8.24486 0 9.35986 0.723 9.35986 2.288V3H11.3599V5.119C11.3599 8 13.0169 13.333 12.0519 13.333C11.6229 13.333 8.93686 14 6.35986 14C3.52586 14 0.663863 13.333 0.663863 13.333C-0.293137 13.333 1.35986 8 1.35986 5.12V3H3.35986ZM4.36286 3H8.35986V2.288C8.35986 1.393 7.75586 1 6.35986 1C4.96786 1 4.36186 1.388 4.36186 2.256V3H4.36286Z"
									fill="white"
								/>
							</svg>
							<p className={`${styles.txt}`}>ADD TO CART</p>
						</div>
						<div className={`${styles.dnf}`}>
							<div className={`${styles.collapse}`}>
								<p className={`${styles.txt_dnf}`}>
									Description & Fit
								</p>
								<svg
									xmlns="http://www.w3.org/2000/svg"
									width="16"
									height="17"
									viewBox="0 0 16 17"
									fill="none"
								>
									<path
										d="M7.99992 12.4499C7.93054 12.45 7.8619 12.4356 7.79837 12.4078C7.73485 12.3799 7.67782 12.3391 7.63092 12.2879L2.13092 6.28793C2.04127 6.19006 1.99418 6.0606 1.99999 5.92801C2.00581 5.79542 2.06405 5.67057 2.16192 5.58093C2.25978 5.49129 2.38925 5.44419 2.52184 5.45C2.65443 5.45582 2.77927 5.51406 2.86892 5.61193L7.99992 11.2099L13.1309 5.61193C13.2206 5.51406 13.3454 5.45582 13.478 5.45C13.6106 5.44419 13.7401 5.49129 13.8379 5.58093C13.9358 5.67057 13.994 5.79542 13.9998 5.92801C14.0057 6.0606 13.9586 6.19006 13.8689 6.28793L8.36892 12.2879C8.32202 12.3391 8.26499 12.3799 8.20146 12.4078C8.13793 12.4356 8.0693 12.45 7.99992 12.4499Z"
										fill="#222222"
									/>
								</svg>
							</div>
							<div className={`${styles.description}`}>
								<p>{productData.description}</p>
							</div>
						</div>
						<form
							className={`${styles.inquiry_form}`}
							onSubmit={saveProduct}
						>
							<input
								type="text"
								className={`${styles.personal_detail}`}
								placeholder="Name"
								name="name"
								value={formData.name}
								onChange={handleChange}
								required
							/>
							<input
								type="email"
								className={`${styles.personal_detail}`}
								placeholder="Email"
								name="email"
								value={formData.email}
								onChange={handleChange}
								required
							/>
							<input
								type="tel"
								className={`${styles.personal_detail}`}
								placeholder="Phone"
								name="mobileNo"
								value={formData.mobileNo}
								onChange={handleChange}
								required
							/>
							<textarea
								className={`${styles.message}`}
								placeholder="message"
								name="message"
								value={formData.message}
								onChange={handleChange}
							></textarea>
							<button
								className={`${styles.send_button}`}
								type="submit"
							>
								SEND
							</button>
						</form>
					</div>
				</>
			</main>
		</>
	);
}
